pipeline {
    agent any

    tools {
        maven 'Maven'  // Use the Maven version configured in Jenkins
        jdk 'jdk-21'          // Use the JDK version configured in Jenkins
    }

    stages {
        stage('Checkout') {
            steps {
                // Checkout the entire repo
                git branch: 'main', url: 'https://github.com/Adithya-Mukkala/Test.git'
            }
        }

        stage('Build') {
            steps {
                // Change directory to MyGitTest before running Maven commands
                bat 'cd MyGitTest && mvn clean compile'
            }
        }

        stage('Test') {
            steps {
                bat 'cd MyGitTest && mvn test'
            }
        }

        stage('Package') {
            steps {
                bat 'cd MyGitTest && mvn package'
            }
        }

    }
}

